name: sonata-connect

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
env:
  GH_USERNAME: ${{ secrets.GH_USERNAME }}
  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: bash run-tests.sh